name: pneuma
version: 0.3.3
description: Web framework with middleware
author: Maxim Savin <i@soulman.kz>
homepage: https://github.com/soulman-is-good/dart-pneuma
dependencies:
  http_server: ">=0.9.8 <1.0.0"
environment:
  sdk: '>=2.0.0 <3.0.0'